import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import { Header, Sidebar } from "@layout";
import { cn } from "@lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={cn(inter.className, "bg-slate-200")}>
        <div className="flex">
          <Sidebar />
          <div className="flex-1">
            <Header />
            <main className="ml-8 mt-8">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
